### PR TITLE
works on latest atom, fixes #1

### LINKED ISSUE #1: Failed to activate the fold-lines package
On starting Atom.

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [fold-lines](https://github.com/alysov/fold-lines) package, v0.1.0
### Stack Trace

Failed to activate the fold-lines package

```
At editor.displayBuffer.getFoldMarkerAttributes is not a function

TypeError: editor.displayBuffer.getFoldMarkerAttributes is not a function
    at /Users/rileyschriner/.atom/packages/fold-lines/lib/fold-lines.coffee:13:57
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at Object.module.exports.FoldLines.activate (/Users/rileyschriner/.atom/packages/fold-lines/lib/fold-lines.coffee:9:39)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:85:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "markdown-preview",
      "wrap-guide",
      "atom-wordpress"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.14
autoclose-html, v0.19.0
emmet, v2.3.17
fold-lines, v0.1.0
git-log, v0.4.1
markdown-preview-plus, v2.2.2
minimap, v4.18.0
my-github-profile, v0.2.1
pigments, v0.19.3
seti-ui, v0.8.1
statusbar-datetime, v0.9.7
wordpress-dictionary, v4.4.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by artemisart**

### CODE REVIEW

File: lib/fold-lines.coffee [hunk 1]
```diff
@@ -7,24 +7,19 @@ module.exports = FoldLines =
...
-      markers = buffer.findMarkers(editor.displayBuffer.getFoldMarkerAttributes())
+      markers = foldsLayer.getMarkers()
       @decorateFold(editor, marker) for marker in markers
-      
+
       # Subscribe to all future folds.
-      @subscriptions.add buffer.onDidCreateMarker (marker) =>
-        @handleBufferMarkerCreated editor, marker
+      @subscriptions.add foldsLayer.onDidCreateMarker (marker) =>
+        @decorateFold editor, marker
```
Comment (alysov) [inline lib/fold-lines.coffee:18]: This sure makes things easier.

**Comment by alysov** [comment]
Thank you for this.  :+1:
